name: 🐛 Bug Report
description: Report a problem or unexpected behavior in the project
title: "[BUG] <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thank you for helping us improve! Please fill out the details below.
  - type: input
    attributes:
      label: 🔖 Bug Title
      description: A short, descriptive title for the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📋 Description
      description: What happened? Provide a clear and concise description.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔁 Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See the error
  - type: textarea
    attributes:
      label: ✅ Expected Behavior
      description: What should happen instead?
  - type: textarea
    attributes:
      label: 💻 Environment Details
      description: Provide details about your setup.
      placeholder: |
        - OS: Windows / macOS / Linux
        - Browser/Framework version
        - Project version
  - type: textarea
    attributes:
      label: 🧩 Possible Solution
      description: If you have a suggestion for fixing the bug, share it here.
  - type: textarea
    attributes:
      label: 📸 Screenshots / Logs
      description: If applicable, add screenshots or logs to help explain your problem.
  - type: checkboxes
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched for similar issues before submitting this one.
        - label: I have provided all relevant information.
        - label: This issue is reproducible.
