name: Bug Report
title: '[BUG] '
labels: [bug, help wanted, hacktoberfest]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true  # Changed from false to true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true  # Added required validation

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen.
      placeholder: Describe the expected behavior...
    validations:
      required: true  # Added required validation

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened.
      placeholder: Describe the actual behavior...
    validations:
      required: true  # Added required validation

  - type: input
    id: screenshots
    attributes:
      label: 📱 Screenshots
      description: URL or path to screenshots if applicable.
      placeholder: https://example.com/screenshot.png
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Desktop, mobile, or application environment details.
      placeholder: |
        - OS: [e.g., Windows 10, macOS Big Sur]
        - Browser: [e.g., Chrome 91, Firefox 89]
        - Node.js version: [e.g., 16.3.0]
        - Database: [e.g., PostgreSQL 13, MongoDB 5.0]
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 🔧 Additional Context
      description: Any other context about the problem.
      placeholder: Additional information...
    validations:
      required: false

  - type: textarea
    id: error_logs
    attributes:
      label: 📊 Error Logs
      description: Paste any relevant error logs here.
      placeholder: |
        Error: [paste error logs here]
        Stack trace: [if available]
    validations:
      required: false

  - type: textarea
    id: possible_solution
    attributes:
      label: 💡 Possible Solution
      description: If you have ideas on how to fix this bug.
      placeholder: Describe possible solution here...
    validations:
      required: false