name: Bug Report
title: '[BUG] '
labels: bug, help wanted, hacktoberfest
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen.
      placeholder: Describe the expected behavior...

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened.
      placeholder: Describe the actual behavior...

  - type: input
    id: screenshots
    attributes:
      label: 📱 Screenshots
      description: URL or path to screenshots if applicable.
      placeholder: https://example.com/screenshot.png

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Desktop, mobile, or application environment details.
      placeholder: OS, Browser, Node.js version, Database, etc.

  - type: textarea
    id: additional_context
    attributes:
      label: 🔧 Additional Context
      description: Any other context about the problem.
      placeholder: Additional information...

  - type: textarea
    id: error_logs
    attributes:
      label: 📊 Error Logs
      description: Paste any relevant error logs here.
      placeholder: Paste logs here...

  - type: textarea
    id: possible_solution
    attributes:
      label: 💡 Possible Solution
      description: If you have ideas on how to fix this bug.
      placeholder: Describe possible solution here...
