name: Bug report
description: Report a bug to help us improve
title: "[BUG] <short description>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug clearly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: List steps to reproduce the issue.
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened?
  - type: textarea
    attributes:
      label: Environment
      description: OS, browser, or framework details.
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other information that might be helpful.
  - type: checkbox
    attributes:
      label: Confirmation
      description: Please confirm the following:
      options:
        - label: I have searched for existing issues and believe this is not a duplicate.
          value: searched
        - label: I have provided all relevant information above.
          value: info
    validations:
      required: true
      minItems: 2
      maxItems: 2
--- IGNORE ---
# This is a bug report template for GitHub issues.